### ISSUE TITLE
Starting fork with active maintenance!

### ISSUE THREAD

**Issue by NikoGrano** [phpWhois/phpWhois#104]
Due lack of maintenance I will continue maintaining this as fork.

https://github.com//Niko9911/phpWhois

**Comment by DavidAnderson684** [comment]
@Niko9911 You've not enabled "Issues" on your fork, so people can't report any issues - is that intentional?

**Comment by NikoGrano** [comment]
@DavidAnderson684 for sure not! Thank you. Will enable them.

**Comment by DavidAnderson684** [comment]
@Niko9911 Thank you. I decided to switch to https://github.com/jsmitty12/phpWhois/ as it appears to be a fork with an ongoing record of maintenance, whereas yours is very new (and perhaps he's already made lots of the fixes you'd intend to make - e.g. he has merged PHP 7.3 compatibility).

**Comment by NikoGrano** [comment]
Closed as non-productive.
