### ISSUE TITLE
No full info from .de zone domains

### ISSUE THREAD

**Issue by neTpyceB** [phpWhois/phpWhois#23]
For example, whois from Terminal:

whois seminarmarkt.de
% Copyright (c) 2010 by DENIC
% Version: 2.0
% 
% Restricted rights.
% 
% Terms and Conditions of Use
% 
% The data in this record is provided by DENIC for informational purposes only.
% DENIC does not guarantee its accuracy and cannot, under any circumstances,
% be held liable in case the stored information would prove to be wrong,
% incomplete or not accurate in any sense.
% 
% All the domain data that is visible in the whois service is protected by law.
% It is not permitted to use it for any purpose other than technical or
% administrative requirements associated with the operation of the Internet.
% It is explicitly forbidden to extract, copy and/or use or re-utilise in any
% form and by any means (electronically or not) the whole or a quantitatively
% or qualitatively substantial part of the contents of the whois database
% without prior and explicit written permission by DENIC.
% It is prohibited, in particular, to use it for transmission of unsolicited
% and/or commercial and/or advertising by phone, fax, e-mail or for any similar
% purposes.
% 
% By maintaining the connection you assure that you have a legitimate interest
% in the data and that you will only use it for the stated purposes. You are
% aware that DENIC maintains the right to initiate legal proceedings against
% you in the event of any breach of this assurance and to bar you from using
% its whois service.
% 
% The DENIC whois service on port 43 never discloses any information concerning
% the domain holder/administrative contact. Information concerning the domain
% holder/administrative contact can be obtained through use of our web-based
% whois service available at the DENIC website:
% http://www.denic.de/en/domains/whois-service/web-whois.html
% 

Domain: seminarmarkt.de
Nserver: b.ns14.net
Nserver: c.ns14.net
Nserver: d.ns14.net
Nserver: ns1.2053.net
Status: connect
Changed: 2011-08-04T14:32:42+02:00

[Tech-C]
Type: PERSON
Name: 2053.net 2053.net
Organisation: 2053.net
Address: Dorfstr. 5B
PostalCode: 24975
City: Weseby
CountryCode: DE
Phone: +49.46349313031
Fax: +49.46349313032
Email: domain@2053.net
Changed: 2006-06-14T16:39:47+02:00

[Zone-C]
Type: PERSON
Name: 2053.net 2053.net
Organisation: 2053.net
Address: Dorfstr. 5B
PostalCode: 24975
City: Weseby
CountryCode: DE
Phone: +49.46349313031
Fax: +49.46349313032
Email: domain@2053.net
Changed: 2006-06-14T16:39:47+02:00

AND Whois usinq library:
[rawdata] => Array
        (
            [0] => Domain: seminarmarkt.de
            [1] => Status: connect
        )

    [regyinfo] => Array
        (
            [servers] => Array
                (
                    [0] => Array
                        (
                            [server] => whois.denic.de
                            [args] => seminarmarkt.de
                            [port] => 43
                        )

                )

            [type] => domain
        )

    [regrinfo] => Array
        (
            [domain] => Array
                (
                    [name] => seminarmarkt.de
                    [nserver] => Array
                        (
                            [c.ns14.net] => 195.34.161.195
                            [ns1.2053.net] => 81.209.141.130
                            [d.ns14.net] => 74.208.254.254
                            [b.ns14.net] => 83.169.55.5
                        )

                )

            [registered] => yes
        )

**Comment by alwoka** [comment]
The is a limitation by the DENIC whois service - see their remarks:

% The DENIC whois service on port 43 never discloses any information concerning
% the domain holder/administrative contact. Information concerning the domain
% holder/administrative contact can be obtained through use of our web-based
% whois service available at the DENIC website:
