### ISSUE TITLE
GoDaddy Whois Problem

### ISSUE THREAD

**Issue by erayaydin** [phpWhois/phpWhois#6]
I'm using phpWhois+cPanelAPI with Laravel. Testing 400-500 domain. But who registrar GoDaddy domains make error.

Error: ErrorException (E_UNKNOWN)  Undefined index: owner
ErrorFile: /vendor/phpwhois/phpwhois/src/whois.gtld.godaddy.php

```
$r = get_blocks($data_str, $items);
$r['owner'] = get_contact($r['owner']); // This line make error
$r['admin'] = get_contact($r['admin'],false,true);
```

I tried with delete whois.gtld.godaddy.php and its works. But its not a good solutions. How can I say "don't use whois.gtld.godaddy.php" or please fix that problem.

**Comment by erayaydin** [comment]
#11 #8 like this...

**Comment by bryceadams** [comment]
Try #21

**Comment by mallardduck** [comment]
@bryceadams it does seem that #21 should fix this, but it doesn't look like that was ever merged in?
